homepage/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('seefriend/', views.seefriend, name='seefriend'),
    path('addfriend/', views.addfriend, name='addfriend'),

    # dilanjutkan ...
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

#Create your models here.
class ClassYear(models.Model):
    YEAR_CHOICES= [('2019', '2019'),
    ('2018', '2018'),
    ('2017', '2017'),
    ('2016', '2016'),
    ('Others', 'Others')]
    year = models.CharField(max_length=255, choices=YEAR_CHOICES, default='NULL')

    def __str__(self):
        return self.year

class Friends(models.Model):
    name = models.CharField(max_length=255, primary_key=True)
    ClassYear = models.ForeignKey(ClassYear, on_delete=models.CASCADE, default='Fasilkom')
    hobby = models.CharField(max_length=255)
    food = models.CharField(max_length=255)
    drink = models.CharField(max_length=255)


    def __str__(self):
        return self.name


homepage/forms.py
from django import forms
from .models import Friends, ClassYear

class FriendForm(forms.ModelForm):
    
    class Meta:
        model = Friends
        fields = ['name', 
        'ClassYear', 
        'hobby', 
        'food', 
        'drink']
        labels = {'name': 'Name',
        'ClassYear': 'Year',
        'hobby': 'Hobby',
        'food': 'Favorite Food',
        'drink': 'Favorite Drink',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Friends, ClassYear
from . import forms

# Create your views here.
def index(request):
    return render(request, 'index.html')

def seefriend(request):
    friends = Friends.objects.all()
    classyear = ClassYear.objects.all()
    response = {'friends' : friends, 'classyear': classyear}
    return render(request, 'seefriend.html', response)

def addfriend(request):
    if request.method == 'POST':
        form = forms.FriendForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:seefriend')
    else:
        form = forms.FriendForm()
    return render(request, 'addfriend.html', {'form': form})

homepage/templates/addfriend.html

{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<title>Add Friends</title>
<br><br><br><br>
<h1 id="profh1">Add Friends</h1>
<form method="post" action="{% url 'homepage:addfriend' %}">
    {% csrf_token %}
    <div style="margin-left: 250px; margin-right: 250px;">
    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            {% for fields in form %}
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <input id="submitBtn" type="submit" class="btn btn-primary" value="Add">
    </div>
</form>
</div>
{% endblock %}

homepage/templates/index.html
{% extends 'navbar.html' %}

{% load static %}

{% block content %}

       
       <p>Welcome to My Website</p>
            <div class="color-overlay"></div>
            
            <section>
                <div class="split right">
                    <h1>Who am I ?</h1>
                    <h2>Muhammad Gibran Raksadinno<br>University of Indonesia<br>Faculty of Computer Science</h2>
                    <h5>A 20 years old CS student that loves to travel, taking photos, playing soccer but hates to code.</h5>
                </div>
                <!-------------------------------->
                <div class="split left">
                    <!-- <p3>This is Me !!!</p3>  -->
                    <img src="{% static 'images/me.JPG' %}" alt="Me">
                    <!-- <img id="arrowlengkung" src="{% static 'images/arrowlengkung.png' %}" alt="arrow"> -->
                </div>
            </section>

            <section id="get-to-know-me">
            <!-- <a>Get to Know Me ...</a> -->
            <!-- <c>Skills</c> -->
<!--      
            <img id="arrow-kanan" src="{% static 'images/arrowlengkung.png' %}" alt="arrow-kanan">
            <img id="arrow-lurus" src="{% static 'images/arrowlurus.png' %}" alt="arrow-lurus">
            <img id="arrow-kiri" src="{% static 'images/arrowlengkung.png' %}" alt="arrow-kiri"> -->
            

            <img id="instagram" src="{% static 'images/instagram.png' %}" alt="instagram"></x>


            <img id="vsco" src="{% static 'images/vsco.png' %}" alt="vsco"></y>


            <img id="flickr" src="{% static 'images/flickr.png' %}" alt="flickr"></z>

          
            <img id="linkedin" src="{% static 'images/linkedin.png' %}" alt="linkedin">

            <img id="python" src="{% static 'images/python.png' %}" alt="python">
            <img id="java" src="{% static 'images/java.png' %}" alt="java">
            <img id="html" src="{% static 'images/html.png' %}" alt="html">
            <img id="css" src="{% static 'images/css.png' %}" alt="css"> 
            </section>

            {% endblock %}

homepage/templates/navbar.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <title>Gibran's Website</title>
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
        </head>

        <body>
            <nav style="color: #26A2D7;">
                <div class="logo">
                    <d>Hello !</d>
                </div>
                <ul class="nav-links">
                    <li>
                        <a style="color: #26A2D7;" href="#">Home</a>
                    </li>
                    <li style="color: #26A2D7;">
                        <a style="color: #26A2D7;" href="#">About</a>
                    </li>
                    <li style="color: #26A2D7;">
                        <a style="color: #26A2D7;" href="#">Work</a>
                    </li>
                    <li style="color: #26A2D7;">
                        <a style="color: #26A2D7;" href="#">Our Project</>a
                    </li>
                    <li style="color: #26A2D7;">
                        <a style="color: #26A2D7;" href='{% url 'homepage:seefriend' %}'>Friends</a>
                    </li>
                </ul>
                <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
                </div>
            </nav>
        {% block content %}

        {% endblock %}

        <script src="{% static 'js/app.js' %}"></script>
    </body>
</html>

homepage/templates/seefriend.html
{% extends 'navbar.html' %}

{% load static %}

{% block content %}
<title>See Friends</title>
<br><br><br><br>
<h1 id=head>Friends List</h1>
<hr>

<div>
  <div class="col-sm-2"></div> 
  <table id="friendtable" style="position: center;" class="table table-hover col-sm-8">
      <thead class="table table-striped table-dark">
        <tr>
          <th scope="col" style="text-align:center">Name</th>
          <th scope="col" style="text-align:center">Batch</th>
          <th scope="col" style="text-align:center">Hobby</th>
          <th scope="col" style="text-align:center">Favorite Food</th>
          <th scope="col" style="text-align:center">Favorite Drink</th>
        </tr>
      </thead>
      <tbody>
        {% for friend in friends %}
          <tr style="background-color: #ED8559 ;">
            <td style="text-align:center">{{ friend.name }}</td>
            <td style="text-align:center">{{ friend.ClassYear }}</td>
            <td style="text-align:center">{{ friend.hobby }}</td>
            <td style="text-align:center">{{ friend.food }}</td>
            <td style="text-align:center">{{ friend.drink }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <div class="col-sm-2"></div>
</div>

<a href="{% url 'homepage:addfriend' %}" style="text-decoration: none;"> 
  <button id="friendButton" type="button" class="btn btn-light">
    Add Friends</button>
</a>

{% endblock %}